name: dart_identity_sdk
description: Just a sdk for identity
version: 5.6.7
homepage: https://github.com/sfperusacdev/dart_identity_sdk

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  devappsdk2: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  http: ^1.2.2
  intl: ">=0.17.0 <=0.19.0"
  kdialogs: ^0.3.0
  package_info_plus: ^8.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shared_preferences_content_provider: ^0.0.5
  shelf: ^1.4.1
  soundpool: ^2.4.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/sounds/qr.mp3
    - assets/sounds/error.mp3
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
